config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)'do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index',as: 'store',via: :all
  end
    #root 'store#index', as: 'store'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progrog Books Online Store</title>
   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
     <%= csrf_meta_tags %>
  </head>

  <body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= image_tag("logo.png")%>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
  <div id="side">
  <div id="cart">
  <%if @cart %>
  <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
    <%= render @cart rescue nil %>
    <%end%>
    <% end %>
  </div>
    <p><%= Time.now.strftime("%I:%M %p") %></p>
    <ul>
      <li><a href="http://www...."><%= t('.home') %></a></li><br/>
      <li><a href="http://www..../faq"><%= t('.questions') %></a></li><br/>
      <li><a href="http://www..../news"><%= t('.news') %></a></li><br/>
      <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
    </ul>

    <% if session[:user_id] %>
    <ul>
    <li><%= link_to 'Orders',orders_path %></li>
    <li><%= link_to 'Products', products_path %></li>
    <li><%= link_to 'Users',users_path%></li>
    </ul>
    <%= button_to 'Logout', logout_path, method: :delete %>
    <% end %>
    <%else%>
    <% unless current_page?(login_path) %>
      <%= link_to 'LOGIN',login_path %>
    <% end %>
    </div>
    <div id="main">
    </div>
    </div>
    <%= yield %>
  </body>
</html>